### ISSUE TITLE
Ajustar info "categoria" no cadastro

### ISSUE THREAD

**Issue by llrt** [alumniime/alumni-ime#1]
Campo obrigatório com seguintes valores:
- Graduado
- Graduado & Professor
- Professor
- Aluno
- Graduação Incompleta

PS: nesse 1o momento não teremos Visitante/Amigo do IME, nem Pós-graduado

**Comment by gabrieldilly** [comment]
Qual será a pergunta para a ser feita para o usuário?
Atualmente está: Como você se encontra hoje:

**Comment by gabrieldilly** [comment]
Seria bom ter uma descrição para cada um dos tipos de usuário para colocar como hint

**Comment by llrt** [comment]
Pode ser "Como você se encontra hoje?" Ou "qual sua relação com o IME hoje?" .
Gostei da ideia do hint. A descrição do hint parece tranquila de você desdobrar @gabrieldilly. Se tiver dificuldade,  fala.
