### ISSUE TITLE
Utilizar outro BD para desenvolvimento

### ISSUE THREAD

**Issue by llrt** [alumniime/alumni-ime#10]
Atualmente a aplicação aponta para um único BD, compartilhado, que virá a ser o de prod. Esse esquema não funcionará muito bem após a 1a subida para prod, porque alterações gerariam efeitos na base ativa do site. Alterar aplicação em desenv para usar BD local ou apontar para um BD compartilhado de desenv.

**Comment by DaviPontes** [comment]
Estamos utilizando um servidor separado para desenvolvimento, lá temos configurado um BD que deve ser usado para testes. Acredito que isso resolva essa questão, por isso irei fechar esse problema.
