### ISSUE TITLE
Separar projetos por semestre

### ISSUE THREAD

**Issue by gabrieldilly** [alumniime/alumni-ime#16]
É necessário dinamizar os links no menu para exibir os projetos separados por data.
E a cada link diferente será filtrado apenas os projetos do respectivo semestre.

@llrt acha melhor usar como filtro apenas a data de submissão?
E como faríamos para gerar o menu? Manualmente?

**Comment by llrt** [comment]
Eu tentaria uma agregação pela data de submissão,  talvez escrevendo uma query especializada, dps paginando nessa query

**Comment by gabrieldilly** [comment]
Adicionei os campos Year e Semester na tabela dos Projetos e o menu é carregadado dinamicamente com os semestres disponíveis para consulta.
